<?php

namespace CarlosGude\BookingBundle\Repository;

/**
 * BookingRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRoomRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBookings($type)
    {

        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder();



        $bookings = $query->select(['r','t'])
                            ->from('CarlosGudeBookingBundle:BookingRoom','r')
                            ->innerJoin('r.bookingElement','t')
                            ->andWhere($query->expr()->eq('r.finalized',true))
                            ->andWhere($query->expr()->eq('t.name',':room'))
                            ->setParameters(['room' => $type]);

        return $bookings->getQuery()->getResult();

    }
}
