<?php

namespace CarlosGude\BookingBundle\Repository;

/**
 * RateBookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateBookingRepository extends \Doctrine\ORM\EntityRepository
{

    public function calculatePrice($booking)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder();


        $rate = $query->select(['r','t'])
                      ->from('AcmeBundle:RateBooking','r')
                      ->innerJoin('r.bookingElement','t')
                      ->where($query->expr()->eq('t.name',':name'))
                      ->setParameters(['name' => $booking->getBookingElement()->getName()]);

        return $rate->getQuery()->getOneOrNullResult();
    }
}
